name: rutube_webview
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  get: 4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: RutubeWebviewPlugin
        dartPluginClass: RutubeWebview
      android:
        package: com.example.rutube_webview
        pluginClass: RutubeWebviewPlugin
